version: "3.3"
services:
  postgres:
    image: "postgres:15.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "xiera"
      POSTGRES_PASSWORD: "xiera"
    volumes:
      - "./data:/var/lib/postgresql/data"